# os.system('CUDA_VISIBLE_DEVICES=2 python train_dota.py '
#           './DOTA_configs/DOTA_hbb/retinanet_r50_fpn_2x_dota.py '
#           '--gpus 1 '
#           '--no-validate '
#           '--work-dir ./results/retinanet_hbb_tv_test')
from EXP_CONFIG.CONFIGS.base import Project_root


def gen_dict(name, config,
             result_root=Project_root + '/results',
             epoch=12,
             result_name='results.pkl',
             gpu_num=1,
             note=''):
    name = 'MMR_AD_' + name
    work_dir = result_root + '/' + name

    return dict(
        name=name,
        config=config,
        work_dir=work_dir,
        cp_file=work_dir+'/epoch_%d.pth' % epoch,
        result=work_dir+'/' + result_name,
        submission_dir=work_dir + '/Task1_results',
        eval_results=work_dir + '/eval_results.json',

        bbox_type='HBB',
        data_type='COCO',
        gpu=gpu_num,
        note=note
    )

root = Project_root + '/M_configs/'
baselines_cfgs = [

    #----------------- Baselines on Data1_DOTA1, 800, 200, 1x, 3x
    gen_dict("G02_Baselines_Data1_DOTA1_M10_RTMDet_L",
             root + "G02_Baselines/Data1_DOTA1/" + "G02_Baselines_Data1_DOTA1_M10_RTMDet_L.py",
             epoch=36, gpu_num=2),
    gen_dict("G02_Baselines_Data1_DOTA1_M1_RtnNetOBB",
             root + "G02_Baselines/Data1_DOTA1/" + "G02_Baselines_Data1_DOTA1_M1_RtnNetOBB.py",
             epoch=12, gpu_num=2),
    gen_dict("G02_Baselines_Data1_DOTA1_M2_RoITrans",
             root + "G02_Baselines/Data1_DOTA1/" + "G02_Baselines_Data1_DOTA1_M2_RoITrans.py",
             epoch=12, gpu_num=2),
    gen_dict("G02_Baselines_Data1_DOTA1_M3_S2ANet",
             root + "G02_Baselines/Data1_DOTA1/" + "G02_Baselines_Data1_DOTA1_M3_S2ANet.py",
             epoch=12, gpu_num=2),
    gen_dict("G02_Baselines_Data1_DOTA1_M4_R3Det_KFIoU",
             root + "G02_Baselines/Data1_DOTA1/" + "G02_Baselines_Data1_DOTA1_M4_R3Det_KFIoU.py",
             epoch=12, gpu_num=2),
    gen_dict("G02_Baselines_Data1_DOTA1_M5_ORCNN_R50",
             root + "G02_Baselines/Data1_DOTA1/" + "G02_Baselines_Data1_DOTA1_M5_ORCNN_R50.py",
             epoch=12, gpu_num=2),
    gen_dict("G02_Baselines_Data1_DOTA1_M6_ORCNN_Swin_T",
             root + "G02_Baselines/Data1_DOTA1/" + "G02_Baselines_Data1_DOTA1_M6_ORCNN_Swin_T.py",
             epoch=12, gpu_num=2),
    gen_dict("G02_Baselines_Data1_DOTA1_M7_ORCNN_ViT_B_MTP",
             root + "G02_Baselines/Data1_DOTA1/" + "G02_Baselines_Data1_DOTA1_M7_ORCNN_ViT_B_MTP.py",
             epoch=12, gpu_num=2),
    # gen_dict("G02_Baselines_Data1_DOTA1_M8_ORCNN_ViT_L_MTP",
    #          root + "G02_Baselines/Data1_DOTA1/" + "G02_Baselines_Data1_DOTA1_M8_ORCNN_ViT_L_MTP.py",
    #          epoch=12, gpu_num=4),
    gen_dict("G02_Baselines_Data1_DOTA1_M9_RTMDet_M",
             root + "G02_Baselines/Data1_DOTA1/" + "G02_Baselines_Data1_DOTA1_M9_RTMDet_M.py",
             epoch=36, gpu_num=2),

    # ----------------- Baselines on Data1_DOTA2, 1024, 500, 1x
    gen_dict("G02_Baselines_Data1_DOTA2_M10_RTMDet_L",
             root + "G02_Baselines/Data1_DOTA2/" + "G02_Baselines_Data1_DOTA2_M10_RTMDet_L.py",
             epoch=12, gpu_num=2),
    gen_dict("G02_Baselines_Data1_DOTA2_M1_RtnNetOBB",
             root + "G02_Baselines/Data1_DOTA2/" + "G02_Baselines_Data1_DOTA2_M1_RtnNetOBB.py",
             epoch=12, gpu_num=2),
    gen_dict("G02_Baselines_Data1_DOTA2_M2_RoITrans",
             root + "G02_Baselines/Data1_DOTA2/" + "G02_Baselines_Data1_DOTA2_M2_RoITrans.py",
             epoch=12, gpu_num=2),
    gen_dict("G02_Baselines_Data1_DOTA2_M3_S2ANet",
             root + "G02_Baselines/Data1_DOTA2/" + "G02_Baselines_Data1_DOTA2_M3_S2ANet.py",
             epoch=12, gpu_num=2),
    gen_dict("G02_Baselines_Data1_DOTA2_M4_R3Det_KFIoU",
             root + "G02_Baselines/Data1_DOTA2/" + "G02_Baselines_Data1_DOTA2_M4_R3Det_KFIoU.py",
             epoch=12, gpu_num=2),
    gen_dict("G02_Baselines_Data1_DOTA2_M5_ORCNN_R50",
             root + "G02_Baselines/Data1_DOTA2/" + "G02_Baselines_Data1_DOTA2_M5_ORCNN_R50.py",
             epoch=12, gpu_num=2),
    gen_dict("G02_Baselines_Data1_DOTA2_M6_ORCNN_Swin_T",
             root + "G02_Baselines/Data1_DOTA2/" + "G02_Baselines_Data1_DOTA2_M6_ORCNN_Swin_T.py",
             epoch=12, gpu_num=2),
    gen_dict("G02_Baselines_Data1_DOTA2_M7_ORCNN_ViT_B_MTP",
             root + "G02_Baselines/Data1_DOTA2/" + "G02_Baselines_Data1_DOTA2_M7_ORCNN_ViT_B_MTP.py",
             epoch=12, gpu_num=2),
    # gen_dict("G02_Baselines_Data1_DOTA2_M8_ORCNN_ViT_L_MTP",
    #          root + "G02_Baselines/Data1_DOTA2/" + "G02_Baselines_Data1_DOTA2_M8_ORCNN_ViT_L_MTP.py",
    #          epoch=12, gpu_num=4),
    gen_dict("G02_Baselines_Data1_DOTA2_M9_RTMDet_M",
             root + "G02_Baselines/Data1_DOTA2/" + "G02_Baselines_Data1_DOTA2_M9_RTMDet_M.py",
             epoch=12, gpu_num=2),

    # ----------------- Baselines on Data2_DIOR_R, 800, 1x, 3x
    gen_dict("G02_Baselines_Data2_DIOR_R_M10_RTMDet_L",
             root + "G02_Baselines/Data2_DIOR_R/" + "G02_Baselines_Data2_DIOR_R_M10_RTMDet_L.py",
             epoch=36, gpu_num=2),
    gen_dict("G02_Baselines_Data2_DIOR_R_M1_RtnNetOBB",
             root + "G02_Baselines/Data2_DIOR_R/" + "G02_Baselines_Data2_DIOR_R_M1_RtnNetOBB.py",
             epoch=12, gpu_num=2),
    gen_dict("G02_Baselines_Data2_DIOR_R_M2_RoITrans",
             root + "G02_Baselines/Data2_DIOR_R/" + "G02_Baselines_Data2_DIOR_R_M2_RoITrans.py",
             epoch=12, gpu_num=2),
    gen_dict("G02_Baselines_Data2_DIOR_R_M3_S2ANet",
             root + "G02_Baselines/Data2_DIOR_R/" + "G02_Baselines_Data2_DIOR_R_M3_S2ANet.py",
             epoch=12, gpu_num=2),
    gen_dict("G02_Baselines_Data2_DIOR_R_M4_R3Det_KFIoU",
             root + "G02_Baselines/Data2_DIOR_R/" + "G02_Baselines_Data2_DIOR_R_M4_R3Det_KFIoU.py",
             epoch=12, gpu_num=2),
    gen_dict("G02_Baselines_Data2_DIOR_R_M5_ORCNN_R50",
             root + "G02_Baselines/Data2_DIOR_R/" + "G02_Baselines_Data2_DIOR_R_M5_ORCNN_R50.py",
             epoch=12, gpu_num=2),
    gen_dict("G02_Baselines_Data2_DIOR_R_M6_ORCNN_Swin_T",
             root + "G02_Baselines/Data2_DIOR_R/" + "G02_Baselines_Data2_DIOR_R_M6_ORCNN_Swin_T.py",
             epoch=12, gpu_num=2),
    gen_dict("G02_Baselines_Data2_DIOR_R_M7_ORCNN_ViT_B_MTP",
             root + "G02_Baselines/Data2_DIOR_R/" + "G02_Baselines_Data2_DIOR_R_M7_ORCNN_ViT_B_MTP.py",
             epoch=12, gpu_num=2),
    # gen_dict("G02_Baselines_Data2_DIOR_R_M8_ORCNN_ViT_L_MTP",
    #          root + "G02_Baselines/Data2_DIOR_R/" + "G02_Baselines_Data2_DIOR_R_M8_ORCNN_ViT_L_MTP.py",
    #          epoch=12, gpu_num=4),
    gen_dict("G02_Baselines_Data2_DIOR_R_M9_RTMDet_M",
             root + "G02_Baselines/Data2_DIOR_R/" + "G02_Baselines_Data2_DIOR_R_M9_RTMDet_M.py",
             epoch=36, gpu_num=2),

    # ----------------- Baselines on Data3_FAIR1M, 800, 400, 1x, ms
    gen_dict("G02_Baselines_Data3_FAIR1M_M10_RTMDet_L",
             root + "G02_Baselines/Data3_FAIR1M/" + "G02_Baselines_Data3_FAIR1M_M10_RTMDet_L.py",
             epoch=12, gpu_num=2),
    gen_dict("G02_Baselines_Data3_FAIR1M_M1_RtnNetOBB",
             root + "G02_Baselines/Data3_FAIR1M/" + "G02_Baselines_Data3_FAIR1M_M1_RtnNetOBB.py",
             epoch=12, gpu_num=2),
    gen_dict("G02_Baselines_Data3_FAIR1M_M2_RoITrans",
             root + "G02_Baselines/Data3_FAIR1M/" + "G02_Baselines_Data3_FAIR1M_M2_RoITrans.py",
             epoch=12, gpu_num=2),
    gen_dict("G02_Baselines_Data3_FAIR1M_M3_S2ANet",
             root + "G02_Baselines/Data3_FAIR1M/" + "G02_Baselines_Data3_FAIR1M_M3_S2ANet.py",
             epoch=12, gpu_num=2),
    gen_dict("G02_Baselines_Data3_FAIR1M_M4_R3Det_KFIoU",
             root + "G02_Baselines/Data3_FAIR1M/" + "G02_Baselines_Data3_FAIR1M_M4_R3Det_KFIoU.py",
             epoch=12, gpu_num=2),
    gen_dict("G02_Baselines_Data3_FAIR1M_M5_ORCNN_R50",
             root + "G02_Baselines/Data3_FAIR1M/" + "G02_Baselines_Data3_FAIR1M_M5_ORCNN_R50.py",
             epoch=12, gpu_num=2),
    gen_dict("G02_Baselines_Data3_FAIR1M_M6_ORCNN_Swin_T",
             root + "G02_Baselines/Data3_FAIR1M/" + "G02_Baselines_Data3_FAIR1M_M6_ORCNN_Swin_T.py",
             epoch=12, gpu_num=2),
    gen_dict("G02_Baselines_Data3_FAIR1M_M7_ORCNN_ViT_B_MTP",
             root + "G02_Baselines/Data3_FAIR1M/" + "G02_Baselines_Data3_FAIR1M_M7_ORCNN_ViT_B_MTP.py",
             epoch=12, gpu_num=2),
    # gen_dict("G02_Baselines_Data3_FAIR1M_M8_ORCNN_ViT_L_MTP",
    #          root + "G02_Baselines/Data3_FAIR1M/" + "G02_Baselines_Data3_FAIR1M_M8_ORCNN_ViT_L_MTP.py",
    #          epoch=12, gpu_num=4),
    gen_dict("G02_Baselines_Data3_FAIR1M_M9_RTMDet_M",
             root + "G02_Baselines/Data3_FAIR1M/" + "G02_Baselines_Data3_FAIR1M_M9_RTMDet_M.py",
             epoch=12, gpu_num=2),

    # ----------------- Baselines on Data5_SpaceNet
    gen_dict("G02_Baselines_Data5_SpaceNet_M10_RTMDet_L",
             root + "G02_Baselines/Data5_SpaceNet/" + "G02_Baselines_Data5_SpaceNet_M10_RTMDet_L.py",
             epoch=36, gpu_num=2),
    gen_dict("G02_Baselines_Data5_SpaceNet_M1_RtnNetOBB",
             root + "G02_Baselines/Data5_SpaceNet/" + "G02_Baselines_Data5_SpaceNet_M1_RtnNetOBB.py",
             epoch=12, gpu_num=2),
    gen_dict("G02_Baselines_Data5_SpaceNet_M2_RoITrans",
             root + "G02_Baselines/Data5_SpaceNet/" + "G02_Baselines_Data5_SpaceNet_M2_RoITrans.py",
             epoch=12, gpu_num=2),
    gen_dict("G02_Baselines_Data5_SpaceNet_M3_S2ANet",
             root + "G02_Baselines/Data5_SpaceNet/" + "G02_Baselines_Data5_SpaceNet_M3_S2ANet.py",
             epoch=12, gpu_num=2),
    gen_dict("G02_Baselines_Data5_SpaceNet_M4_R3Det_KFIoU",
             root + "G02_Baselines/Data5_SpaceNet/" + "G02_Baselines_Data5_SpaceNet_M4_R3Det_KFIoU.py",
             epoch=12, gpu_num=2),
    gen_dict("G02_Baselines_Data5_SpaceNet_M5_ORCNN_R50",
             root + "G02_Baselines/Data5_SpaceNet/" + "G02_Baselines_Data5_SpaceNet_M5_ORCNN_R50.py",
             epoch=12, gpu_num=2),
    gen_dict("G02_Baselines_Data5_SpaceNet_M6_ORCNN_Swin_T",
             root + "G02_Baselines/Data5_SpaceNet/" + "G02_Baselines_Data5_SpaceNet_M6_ORCNN_Swin_T.py",
             epoch=12, gpu_num=2),
    gen_dict("G02_Baselines_Data5_SpaceNet_M7_ORCNN_ViT_B_MTP",
             root + "G02_Baselines/Data5_SpaceNet/" + "G02_Baselines_Data5_SpaceNet_M7_ORCNN_ViT_B_MTP.py",
             epoch=12, gpu_num=2),
    # gen_dict("G02_Baselines_Data5_SpaceNet_M8_ORCNN_ViT_L_MTP",
    #          root + "G02_Baselines/Data5_SpaceNet/" + "G02_Baselines_Data5_SpaceNet_M8_ORCNN_ViT_L_MTP.py",
    #          epoch=12, gpu_num=4),
    gen_dict("G02_Baselines_Data5_SpaceNet_M9_RTMDet_M",
             root + "G02_Baselines/Data5_SpaceNet/" + "G02_Baselines_Data5_SpaceNet_M9_RTMDet_M.py",
             epoch=36, gpu_num=2),

    # ----------------- Baselines on Data6_Xview
    gen_dict("G02_Baselines_Data6_Xview_M10_RTMDet_L",
             root + "G02_Baselines/Data6_Xview/" + "G02_Baselines_Data6_Xview_M10_RTMDet_L.py",
             epoch=36, gpu_num=2),
    gen_dict("G02_Baselines_Data6_Xview_M1_RtnNetOBB",
             root + "G02_Baselines/Data6_Xview/" + "G02_Baselines_Data6_Xview_M1_RtnNetOBB.py",
             epoch=12, gpu_num=2),
    gen_dict("G02_Baselines_Data6_Xview_M2_RoITrans",
             root + "G02_Baselines/Data6_Xview/" + "G02_Baselines_Data6_Xview_M2_RoITrans.py",
             epoch=12, gpu_num=2),
    gen_dict("G02_Baselines_Data6_Xview_M3_S2ANet",
             root + "G02_Baselines/Data6_Xview/" + "G02_Baselines_Data6_Xview_M3_S2ANet.py",
             epoch=12, gpu_num=2),
    gen_dict("G02_Baselines_Data6_Xview_M4_R3Det_KFIoU",
             root + "G02_Baselines/Data6_Xview/" + "G02_Baselines_Data6_Xview_M4_R3Det_KFIoU.py",
             epoch=12, gpu_num=2),
    gen_dict("G02_Baselines_Data6_Xview_M5_ORCNN_R50",
             root + "G02_Baselines/Data6_Xview/" + "G02_Baselines_Data6_Xview_M5_ORCNN_R50.py",
             epoch=12, gpu_num=2),
    gen_dict("G02_Baselines_Data6_Xview_M6_ORCNN_Swin_T",
             root + "G02_Baselines/Data6_Xview/" + "G02_Baselines_Data6_Xview_M6_ORCNN_Swin_T.py",
             epoch=12, gpu_num=2),
    gen_dict("G02_Baselines_Data6_Xview_M7_ORCNN_ViT_B_MTP",
             root + "G02_Baselines/Data6_Xview/" + "G02_Baselines_Data6_Xview_M7_ORCNN_ViT_B_MTP.py",
             epoch=12, gpu_num=2),
    # gen_dict("G02_Baselines_Data6_Xview_M8_ORCNN_ViT_L_MTP",
    #          root + "G02_Baselines/Data6_Xview/" + "G02_Baselines_Data6_Xview_M8_ORCNN_ViT_L_MTP.py",
    #          epoch=12, gpu_num=4),
    gen_dict("G02_Baselines_Data6_Xview_M9_RTMDet_M",
             root + "G02_Baselines/Data6_Xview/" + "G02_Baselines_Data6_Xview_M9_RTMDet_M.py",
             epoch=36, gpu_num=2),

    # ----------------- Baselines on Data7_HRSC2016
    gen_dict("G02_Baselines_Data7_HRSC2016_M10_RTMDet_L",
             root + "G02_Baselines/Data7_HRSC2016/" + "G02_Baselines_Data7_HRSC2016_M10_RTMDet_L.py",
             epoch=36 * 3, gpu_num=2),
    gen_dict("G02_Baselines_Data7_HRSC2016_M1_RtnNetOBB",
             root + "G02_Baselines/Data7_HRSC2016/" + "G02_Baselines_Data7_HRSC2016_M1_RtnNetOBB.py",
             epoch=36 * 3, gpu_num=2),
    gen_dict("G02_Baselines_Data7_HRSC2016_M2_RoITrans",
             root + "G02_Baselines/Data7_HRSC2016/" + "G02_Baselines_Data7_HRSC2016_M2_RoITrans.py",
             epoch=36, gpu_num=2),
    gen_dict("G02_Baselines_Data7_HRSC2016_M3_S2ANet",
             root + "G02_Baselines/Data7_HRSC2016/" + "G02_Baselines_Data7_HRSC2016_M3_S2ANet.py",
             epoch=36, gpu_num=2),
    gen_dict("G02_Baselines_Data7_HRSC2016_M4_R3Det_KFIoU",
             root + "G02_Baselines/Data7_HRSC2016/" + "G02_Baselines_Data7_HRSC2016_M4_R3Det_KFIoU.py",
             epoch=36, gpu_num=2),
    gen_dict("G02_Baselines_Data7_HRSC2016_M5_ORCNN_R50",
             root + "G02_Baselines/Data7_HRSC2016/" + "G02_Baselines_Data7_HRSC2016_M5_ORCNN_R50.py",
             epoch=36, gpu_num=2),
    gen_dict("G02_Baselines_Data7_HRSC2016_M6_ORCNN_Swin_T",
             root + "G02_Baselines/Data7_HRSC2016/" + "G02_Baselines_Data7_HRSC2016_M6_ORCNN_Swin_T.py",
             epoch=36, gpu_num=2),
    gen_dict("G02_Baselines_Data7_HRSC2016_M7_ORCNN_ViT_B_MTP",
             root + "G02_Baselines/Data7_HRSC2016/" + "G02_Baselines_Data7_HRSC2016_M7_ORCNN_ViT_B_MTP.py",
             epoch=36, gpu_num=2),
    # gen_dict("G02_Baselines_Data7_HRSC2016_M8_ORCNN_ViT_L_MTP",
    #          root + "G02_Baselines/Data7_HRSC2016/" + "G02_Baselines_Data7_HRSC2016_M8_ORCNN_ViT_L_MTP.py",
    #          epoch=36, gpu_num=4),
    gen_dict("G02_Baselines_Data7_HRSC2016_M9_RTMDet_M",
             root + "G02_Baselines/Data7_HRSC2016/" + "G02_Baselines_Data7_HRSC2016_M9_RTMDet_M.py",
             epoch=36 * 3, gpu_num=2),

    # ----------------- Baselines on Data8_GLH_Bridge
    gen_dict("G02_Baselines_Data8_GLH_Bridge_M10_RTMDet_L",
             root + "G02_Baselines/Data8_GLH_Bridge/" + "G02_Baselines_Data8_GLH_Bridge_M10_RTMDet_L.py",
             epoch=36, gpu_num=2),
    gen_dict("G02_Baselines_Data8_GLH_Bridge_M1_RtnNetOBB",
             root + "G02_Baselines/Data8_GLH_Bridge/" + "G02_Baselines_Data8_GLH_Bridge_M1_RtnNetOBB.py",
             epoch=12, gpu_num=2),
    gen_dict("G02_Baselines_Data8_GLH_Bridge_M2_RoITrans",
             root + "G02_Baselines/Data8_GLH_Bridge/" + "G02_Baselines_Data8_GLH_Bridge_M2_RoITrans.py",
             epoch=12, gpu_num=2),
    gen_dict("G02_Baselines_Data8_GLH_Bridge_M3_S2ANet",
             root + "G02_Baselines/Data8_GLH_Bridge/" + "G02_Baselines_Data8_GLH_Bridge_M3_S2ANet.py",
             epoch=12, gpu_num=2),
    gen_dict("G02_Baselines_Data8_GLH_Bridge_M4_R3Det_KFIoU",
             root + "G02_Baselines/Data8_GLH_Bridge/" + "G02_Baselines_Data8_GLH_Bridge_M4_R3Det_KFIoU.py",
             epoch=12, gpu_num=2),
    gen_dict("G02_Baselines_Data8_GLH_Bridge_M5_ORCNN_R50",
             root + "G02_Baselines/Data8_GLH_Bridge/" + "G02_Baselines_Data8_GLH_Bridge_M5_ORCNN_R50.py",
             epoch=12, gpu_num=2),
    gen_dict("G02_Baselines_Data8_GLH_Bridge_M6_ORCNN_Swin_T",
             root + "G02_Baselines/Data8_GLH_Bridge/" + "G02_Baselines_Data8_GLH_Bridge_M6_ORCNN_Swin_T.py",
             epoch=12, gpu_num=2),
    gen_dict("G02_Baselines_Data8_GLH_Bridge_M7_ORCNN_ViT_B_MTP",
             root + "G02_Baselines/Data8_GLH_Bridge/" + "G02_Baselines_Data8_GLH_Bridge_M7_ORCNN_ViT_B_MTP.py",
             epoch=12, gpu_num=2),
    # gen_dict("G02_Baselines_Data8_GLH_Bridge_M8_ORCNN_ViT_L_MTP",
    #          root + "G02_Baselines/Data8_GLH_Bridge/" + "G02_Baselines_Data8_GLH_Bridge_M8_ORCNN_ViT_L_MTP.py",
    #          epoch=12, gpu_num=4),
    gen_dict("G02_Baselines_Data8_GLH_Bridge_M9_RTMDet_M",
             root + "G02_Baselines/Data8_GLH_Bridge/" + "G02_Baselines_Data8_GLH_Bridge_M9_RTMDet_M.py",
             epoch=36, gpu_num=2),



    # ----------------- Baselines on Data11_WHU_Mix
    gen_dict("G02_Baselines_Data11_WHU_Mix_M10_RTMDet_L",
             root + "G02_Baselines/Data11_WHU_Mix/" + "G02_Baselines_Data11_WHU_Mix_M10_RTMDet_L.py",
             epoch=36, gpu_num=2),
    gen_dict("G02_Baselines_Data11_WHU_Mix_M1_RtnNetOBB",
             root + "G02_Baselines/Data11_WHU_Mix/" + "G02_Baselines_Data11_WHU_Mix_M1_RtnNetOBB.py",
             epoch=12, gpu_num=2),
    gen_dict("G02_Baselines_Data11_WHU_Mix_M2_RoITrans",
             root + "G02_Baselines/Data11_WHU_Mix/" + "G02_Baselines_Data11_WHU_Mix_M2_RoITrans.py",
             epoch=12, gpu_num=2),
    gen_dict("G02_Baselines_Data11_WHU_Mix_M3_S2ANet",
             root + "G02_Baselines/Data11_WHU_Mix/" + "G02_Baselines_Data11_WHU_Mix_M3_S2ANet.py",
             epoch=12, gpu_num=2),
    gen_dict("G02_Baselines_Data11_WHU_Mix_M4_R3Det_KFIoU",
             root + "G02_Baselines/Data11_WHU_Mix/" + "G02_Baselines_Data11_WHU_Mix_M4_R3Det_KFIoU.py",
             epoch=12, gpu_num=2),
    gen_dict("G02_Baselines_Data11_WHU_Mix_M5_ORCNN_R50",
             root + "G02_Baselines/Data11_WHU_Mix/" + "G02_Baselines_Data11_WHU_Mix_M5_ORCNN_R50.py",
             epoch=12, gpu_num=2),
    gen_dict("G02_Baselines_Data11_WHU_Mix_M6_ORCNN_Swin_T",
             root + "G02_Baselines/Data11_WHU_Mix/" + "G02_Baselines_Data11_WHU_Mix_M6_ORCNN_Swin_T.py",
             epoch=12, gpu_num=2),
    gen_dict("G02_Baselines_Data11_WHU_Mix_M7_ORCNN_ViT_B_MTP",
             root + "G02_Baselines/Data11_WHU_Mix/" + "G02_Baselines_Data11_WHU_Mix_M7_ORCNN_ViT_B_MTP.py",
             epoch=12, gpu_num=2),
    gen_dict("G02_Baselines_Data11_WHU_Mix_M8_ORCNN_ViT_L_MTP",
             root + "G02_Baselines/Data11_WHU_Mix/" + "G02_Baselines_Data11_WHU_Mix_M8_ORCNN_ViT_L_MTP.py",
             epoch=12, gpu_num=4),
    gen_dict("G02_Baselines_Data11_WHU_Mix_M9_RTMDet_M",
             root + "G02_Baselines/Data11_WHU_Mix/" + "G02_Baselines_Data11_WHU_Mix_M9_RTMDet_M.py",
             epoch=36, gpu_num=2),

    # ----------------- Baselines on Data12_ShipImageNet
    gen_dict("G02_Baselines_Data12_ShipImageNet_M10_RTMDet_L",
             root + "G02_Baselines/Data12_ShipImageNet/" + "G02_Baselines_Data12_ShipImageNet_M10_RTMDet_L.py",
             epoch=36 * 3, gpu_num=2),
    gen_dict("G02_Baselines_Data12_ShipImageNet_M1_RtnNetOBB",
             root + "G02_Baselines/Data12_ShipImageNet/" + "G02_Baselines_Data12_ShipImageNet_M1_RtnNetOBB.py",
             epoch=36 * 3, gpu_num=2),
    gen_dict("G02_Baselines_Data12_ShipImageNet_M2_RoITrans",
             root + "G02_Baselines/Data12_ShipImageNet/" + "G02_Baselines_Data12_ShipImageNet_M2_RoITrans.py",
             epoch=12 * 3, gpu_num=2),
    gen_dict("G02_Baselines_Data12_ShipImageNet_M3_S2ANet",
             root + "G02_Baselines/Data12_ShipImageNet/" + "G02_Baselines_Data12_ShipImageNet_M3_S2ANet.py",
             epoch=12 * 3, gpu_num=2),
    gen_dict("G02_Baselines_Data12_ShipImageNet_M4_R3Det_KFIoU",
             root + "G02_Baselines/Data12_ShipImageNet/" + "G02_Baselines_Data12_ShipImageNet_M4_R3Det_KFIoU.py",
             epoch=12 * 3, gpu_num=2),
    gen_dict("G02_Baselines_Data12_ShipImageNet_M5_ORCNN_R50",
             root + "G02_Baselines/Data12_ShipImageNet/" + "G02_Baselines_Data12_ShipImageNet_M5_ORCNN_R50.py",
             epoch=12 * 3, gpu_num=2),
    gen_dict("G02_Baselines_Data12_ShipImageNet_M6_ORCNN_Swin_T",
             root + "G02_Baselines/Data12_ShipImageNet/" + "G02_Baselines_Data12_ShipImageNet_M6_ORCNN_Swin_T.py",
             epoch=12 * 3, gpu_num=2),
    gen_dict("G02_Baselines_Data12_ShipImageNet_M7_ORCNN_ViT_B_MTP",
             root + "G02_Baselines/Data12_ShipImageNet/" + "G02_Baselines_Data12_ShipImageNet_M7_ORCNN_ViT_B_MTP.py",
             epoch=12 * 3, gpu_num=2),
    # gen_dict("G02_Baselines_Data12_ShipImageNet_M8_ORCNN_ViT_L_MTP",
    #          root + "G02_Baselines/Data12_ShipImageNet/" + "G02_Baselines_Data12_ShipImageNet_M8_ORCNN_ViT_L_MTP.py",
    #          epoch=12 * 3, gpu_num=4),
    gen_dict("G02_Baselines_Data12_ShipImageNet_M9_RTMDet_M",
             root + "G02_Baselines/Data12_ShipImageNet/" + "G02_Baselines_Data12_ShipImageNet_M9_RTMDet_M.py",
             epoch=36 * 3, gpu_num=2),
    ################################################################################
    gen_dict("G02_Fair_Baselines_Data1_DOTA1_M10_RTMDet_L",
             root + "G02_Baselines/Data1_DOTA1/" + "G02_Fair_Baselines_Data1_DOTA1_M10_RTMDet_L.py",
             epoch=12, gpu_num=2),
    gen_dict("G02_Fair_Baselines_Data1_DOTA2_M10_RTMDet_L",
             root + "G02_Baselines/Data1_DOTA2/" + "G02_Fair_Baselines_Data1_DOTA2_M10_RTMDet_L.py",
             epoch=12, gpu_num=2),
    gen_dict("G02_Fair_Baselines_Data2_DIOR_R_M10_RTMDet_L",
             root + "G02_Baselines/Data2_DIOR_R/" + "G02_Fair_Baselines_Data2_DIOR_R_M10_RTMDet_L.py",
             epoch=12, gpu_num=2),
    gen_dict("G02_Fair_Baselines_Data3_FAIR1M_M10_RTMDet_L",
             root + "G02_Baselines/Data3_FAIR1M/" + "G02_Fair_Baselines_Data3_FAIR1M_M10_RTMDet_L.py",
             epoch=12, gpu_num=2),
    gen_dict("G02_Fair_Baselines_Data5_SpaceNet_M10_RTMDet_L",
             root + "G02_Baselines/Data5_SpaceNet/" + "G02_Fair_Baselines_Data5_SpaceNet_M10_RTMDet_L.py",
             epoch=12, gpu_num=2),
    gen_dict("G02_Fair_Baselines_Data6_Xview_M10_RTMDet_L",
             root + "G02_Baselines/Data6_Xview/" + "G02_Fair_Baselines_Data6_Xview_M10_RTMDet_L.py",
             epoch=12, gpu_num=2),
    gen_dict("G02_Fair_Baselines_Data7_HRSC2016_M10_RTMDet_L",
             root + "G02_Baselines/Data7_HRSC2016/" + "G02_Fair_Baselines_Data7_HRSC2016_M10_RTMDet_L.py",
             epoch=12, gpu_num=2),
    gen_dict("G02_Fair_Baselines_Data11_WHU_Mix_M10_RTMDet_L",
             root + "G02_Baselines/Data11_WHU_Mix/" + "G02_Fair_Baselines_Data11_WHU_Mix_M10_RTMDet_L.py",
             epoch=12, gpu_num=2),
]



baselines_cfgs = {cfg.pop('name'):cfg for cfg in baselines_cfgs}

def show_dict(d, n):
    for k,v in d.items():
        print('    ' * n, end='')
        if isinstance(v, dict):
            print(k, ':')
            show_dict(v, n+1)
        else:
            print(k, ':', v)
if __name__ == '__main__':
    show_dict(baselines_cfgs, 0)

