data_infos = dict(
    Data1_DOTA2=dict(
        data_root='./data/DOTA2_1024_500',
        train_img_dir='train/images',
        train_ann_dir='train/Step6_Format_labels',
        val_img_dir='ss_val/images',
        val_ann_dir='ss_val/annfiles',
        class_names=['airport', 'baseball-diamond', 'basketball-court', 'bridge',
                     'container-crane', 'ground-track-field', 'harbor', 'helicopter', 'helipad',
                     'large-vehicle', 'plane', 'roundabout',
                     'ship', 'small-vehicle', 'soccer-ball-field',
                     'storage-tank', 'swimming-pool', 'tennis-court'],
        img_scale=(1024, 1024),
        val_dataset_flag='D1_DOTA2',
        support_data='./data/DOTA2_1024_500/train/Step5_3_Prepare_Visual_Text_DINOv2_support.pkl',
    ),
    Data1_DOTA1=dict(
        data_root='./data/DOTA_800_600',
        train_img_dir='train/images',
        train_ann_dir='train/annotations',
        val_img_dir='val/images',
        val_ann_dir='val/labelTxt',
        class_names=['baseball-diamond', 'basketball-court', 'bridge', 'ground-track-field', 'harbor', 'helicopter',
                     'large-vehicle', 'plane', 'roundabout', 'ship', 'small-vehicle', 'soccer-ball-field',
                     'storage-tank', 'swimming-pool', 'tennis-court'],
        img_scale=(800, 800),
        val_dataset_flag='D1_DOTA1',
        support_data='./data/DOTA_800_600/train/Step5_3_Prepare_Visual_Text_DINOv2_support.pkl',

    ),
    Data2_DIOR_R=dict(
        data_root='./data/DIOR_R_dota',
        train_img_dir='train_val/images',
        train_ann_dir='train_val/Step6_Format_labels',
        val_img_dir='test/images',
        val_ann_dir='test/labelTxt',
        class_names=['airplane', 'airport', 'baseballfield', 'basketballcourt',
                     'bridge', 'chimney', 'dam',
                     'Expressway-Service-area', 'Expressway-toll-station',
                     'golffield', 'groundtrackfield',
                     'harbor', 'overpass', 'ship', 'stadium', 'storagetank',
                     'tenniscourt', 'trainstation', 'vehicle', 'windmill'],
        img_scale=(800, 800),
        val_dataset_flag='D2_DIOR_R',
        support_data='./data/DIOR_R_dota/train_val/Step5_3_Prepare_Visual_Text_DINOv2_support.pkl',

    ),
    Data3_FAIR1M=dict(
        data_root='./data/FAIR1M_2_800_400',
        train_img_dir='train/images',
        train_ann_dir='train/Step6_Format_labels',
        val_img_dir='val/images',
        val_ann_dir='val/annfiles',
        class_names=['a220', 'a321', 'a330', 'a350', 'arj21',
                     'baseball_field', 'basketball_court', 'boeing737', 'boeing747', 'boeing777', 'boeing787',
                     'bridge', 'bus', 'c919', 'cargo_truck', 'dry_cargo_ship', 'dump_truck',
                     'engineering_ship', 'excavator', 'fishing_boat', 'football_field', 'intersection',
                     'liquid_cargo_ship', 'motorboat', 'other-airplane', 'other-ship', 'other-vehicle',
                     'passenger_ship', 'roundabout',
                     'small_car', 'tennis_court', 'tractor', 'trailer', 'truck_tractor', 'tugboat', 'van', 'warship'],
        img_scale=(1024, 1024),
        val_dataset_flag='D3_FAIR1M',
        support_data='./data/FAIR1M_2_800_400/train/Step5_3_Prepare_Visual_Text_DINOv2_support.pkl',

    ),
    Data4_HRRSD=dict(
        data_root='./data/TGRS_HRRSD',
        train_img_dir=None,
        train_ann_dir=None,
        val_img_dir='test/images',
        val_ann_dir='test/Step1_Trans_HBB2OBB',
        class_names=['airplane', 'baseball_diamond', 'basketball_court',
                       'bridge', 'crossroad', 'ground_track_field',
                       'harbor', 'parking_lot', 'ship', 'storage_tank',
                       't_junction', 'tennis_court', 'vehicle'],
        img_scale=(832, 832),
        val_dataset_flag='D4_HRRSD',
        support_data='./data/TGRS_HRRSD/train_val/Step5_3_Prepare_Visual_Text_DINOv2_support.pkl',

    ),
    Data5_SpaceNet=dict(
        data_root='./data/Spacenet_Merge',
        train_img_dir='train/images',
        train_ann_dir='train/Step6_Format_labels',
        val_img_dir='val/images',
        val_ann_dir='val/annotations',
        class_names=['building',],
        img_scale=(832, 832),
        val_dataset_flag='D5_SpaceNet',
        support_data='./data/Spacenet_Merge/train/Step5_3_Prepare_Visual_Text_DINOv2_support.pkl',

    ),
    # Data5_SpaceNet_Paris=dict(
    #     data_root='./data/spacenet/AOI_3_Paris_Train',
    #     train_img_dir=None,
    #     train_ann_dir=None,
    #     val_img_dir='val/JPEGImages_png',
    #     val_ann_dir='val/labelTxt',
    #     class_names=['building', ],
    #     img_scale=(832, 832),
    #     val_dataset_flag='D5_SpaceNet',
    #     support_data='./data/Spacenet_Merge/Step5_3_Prepare_Visual_Text_DINOv2_support.pkl',
    # ),
    # Data5_SpaceNet_Shanghai=dict(
    #     data_root='./data/spacenet/AOI_4_Shanghai_Train',
    #     train_img_dir=None,
    #     train_ann_dir=None,
    #     val_img_dir='val/JPEGImages_png',
    #     val_ann_dir='val/labelTxt',
    #     class_names=['building', ],
    #     img_scale=(832, 832),
    #     val_dataset_flag='D5_SpaceNet',
    #     support_data='./data/Spacenet_Merge/Step5_3_Prepare_Visual_Text_DINOv2_support.pkl',
    # ),
    # Data5_SpaceNet_Khartoum=dict(
    #     data_root='./data/spacenet/AOI_5_Khartoum_Train',
    #     train_img_dir=None,
    #     train_ann_dir=None,
    #     val_img_dir='val/JPEGImages_png',
    #     val_ann_dir='val/labelTxt',
    #     class_names=['building', ],
    #     img_scale=(832, 832),
    #     val_dataset_flag='D5_SpaceNet',
    #     support_data='./data/Spacenet_Merge/Step5_3_Prepare_Visual_Text_DINOv2_support.pkl',
    # ),
    Data6_Xview=dict(
        data_root='./data/xView_New_800_600',
        train_img_dir='train/images',
        train_ann_dir='train/Step6_Format_labels',
        val_img_dir='test/images',
        val_ann_dir='test/Step1_Trans_HBB2OBB',
        class_names=['Aircraft_Hangar', 'Barge', 'Building', 'Bus', 'Cargo_Truck',
                     'Cargo_or_Container_Car', 'Cement_Mixer', 'Construction_Site',
                     'Container_Crane', 'Container_Ship', 'Crane_Truck', 'Damaged_Building',
                     'Dump_Truck', 'Engineering_Vehicle', 'Excavator', 'Facility', 'Ferry', 'Fishing_Vessel',
                     'Fixed-wing_Aircraft', 'Flat_Car', 'Front_loader_or_Bulldozer', 'Ground_Grader',
                     'Haul_Truck', 'Helicopter', 'Helipad', 'Hut_or_Tent', 'Locomotive', 'Maritime_Vessel',
                     'Mobile_Crane', 'Motorboat', 'Oil_Tanker', 'Passenger_Car', 'Passenger_Vehicle',
                     'Passenger_or_Cargo_Plane', 'Pickup_Truck', 'Pylon', 'Railway_Vehicle', 'Reach_Stacker',
                     'Sailboat', 'Scraper_or_Tractor', 'Shed', 'Shipping_Container', 'Shipping_container_lot',
                     'Small_Aircraft', 'Small_Car', 'Storage_Tank', 'Straddle_Carrier', 'Tank_car', 'Tower',
                     'Tower_crane', 'Trailer', 'Truck', 'Truck_Tractor', 'Truck_Tractor_with_Box_Trailer',
                     'Truck_Tractor_with_Flatbed_Trailer', 'Truck_Tractor_with_Liquid_Tank', 'Tugboat',
                     'Utility_Truck', 'Vehicle_Lot', 'Yacht'],
        img_scale=(800, 800),
        val_dataset_flag='D6_Xview',
        support_data= './data/xView_New_800_600/train/Step5_3_Prepare_Visual_Text_DINOv2_support.pkl',
    ),
    Data7_HRSC2016=dict(
        data_root='./data/HRSC2016_DOTA',
        train_img_dir='train/images',
        train_ann_dir='train/Step6_Format_labels',
        val_img_dir='test/images',
        val_ann_dir='test/labelTxt',
        class_names=['Arleigh_Burke', 'Austen', 'Car_carrier', 'CntShip', 'Container', 'Cruise',
                     'Enterprise', 'Hovercraft', 'Kuznetsov', 'Medical', 'Midway_class', 'Nimitz',
                     'OXo', 'Perry', 'Sanantonio', 'Tarawa', 'Ticonderoga',
                     'WhidbeyIsland', 'aircraft_carrier','lute', 'merchant_ship', 'ship', 'submarine', 'warcraft', 'yacht'],

        img_scale=(800, 800),
        val_dataset_flag='D7_HRSC2016',
        support_data='./data/HRSC2016_DOTA/train/Step5_3_Prepare_Visual_Text_DINOv2_support_New.pkl',
    ),
    Data8_GLH_Bridge=dict(
        data_root='./data//GLH-Bridge_1024_200',
        train_img_dir='train/images',
        train_ann_dir='train/Step6_Format_labels',
        val_img_dir='val/images',
        val_ann_dir='val/annfiles',
        class_names=['bridge',],
        img_scale=(800, 800),
        val_dataset_flag='D8_GLH_Bridge',
        support_data='./data/GLH-Bridge_1024_200/train/Step5_3_Prepare_Visual_Text_DINOv2_support.pkl',
    ),
    Data9_FMoW=dict(
        data_root='./data/FMoW',
        train_img_dir='train/images',
        train_ann_dir='train/Step6_Format_labels',
        val_img_dir='test/images',
        val_ann_dir='test/labelTxt',
        class_names=['airport', 'airport_hangar', 'airport_terminal', 'amusement_park', 'archaeological_site',
                     'border_checkpoint', 'burial_site', 'car_dealership', 'construction_site',
                     'dam', 'educational_institution', 'electric_substation', 'factory_or_powerplant',
                     'fountain', 'gas_station', 'golf_course', 'ground_transportation_station', 'helipad',
                     'interchange', 'lake_or_pond', 'lighthouse', 'military_facility', 'nuclear_powerplant',
                     'oil_or_gas_facility', 'park', 'parking_lot_or_garage', 'port', 'race_track', 'railway_bridge',
                     'recreational_facility', 'road_bridge', 'runway', 'shipyard', 'shopping_mall',
                     'smokestack', 'solar_farm', 'space_facility', 'stadium'],
        img_scale=(800, 800),
        val_dataset_flag='D9_FMoW',
        support_data='./data/FMoW/train/Step5_3_Prepare_Visual_Text_DINOv2_support.pkl',
    ),

    Data11_WHU_Mix=dict(
        data_root='./data/WHU_Mix',
        train_img_dir='train/images',
        train_ann_dir='train/Step6_Format_labels_wo_embeds',
        val_img_dir='val/images',
        val_ann_dir='val/labelTxt',
        class_names=['building',],
        img_scale=(800, 800),
        val_dataset_flag='Data11_WHU_Mix',
        support_data='./data/WHU_Mix/train/Step5_3_Prepare_Visual_Text_DINOv2_support.pkl',
    ),
    Data12_ShipImageNet=dict(
        data_root='./data/ShipRSImageNet_DOTA',
        train_img_dir='train/images',
        train_ann_dir='train/Step6_Format_labels',
        val_img_dir='val/images',
        val_ann_dir='val/labelTxt',
        class_names=['aoe', 'arleigh_burke_dd', 'asagiri_dd', 'atago_dd',
                     'austin_ll', 'barge', 'cargo', 'commander', 'container_ship', 'dock',
                     'enterprise', 'epf', 'ferry', 'fishing_vessel', 'hatsuyuki_dd', 'hovercraft',
                     'hyuga_dd', 'lha_ll', 'lsd_41_ll', 'masyuu_as', 'medical_ship', 'midway',
                     'motorboat', 'nimitz', 'oil_tanker', 'osumi_ll', 'other_aircraft_carrier',
                     'other_auxiliary_ship', 'other_destroyer', 'other_frigate', 'other_landing',
                     'other_merchant', 'other_ship', 'other_warship', 'patrol', 'perry_ff', 'roro',
                     'sailboat', 'sanantonio_as', 'submarine', 'test_ship', 'ticonderoga',
                     'training_ship', 'tugboat', 'wasp_ll', 'yacht', 'yudao_ll', 'yudeng_ll', 'yuting_ll', 'yuzhao_ll'],
        img_scale=(800, 800),
        val_dataset_flag='Data12_ShipImageNet',
        support_data='./data/ShipRSImageNet_DOTA/train/Step5_3_Prepare_Visual_Text_DINOv2_support.pkl',
    ),

)