train_cfgs = dict(
    Data1_DOTA2=dict(
        data_root='./data/DOTA2_1024_500/train',
        img_dir='images',
        ann_dir='annfiles',
        pkl_ann_dir='Step6_Format_labels',
        class_names=['airport', 'baseball-diamond', 'basketball-court', 'bridge',
                     'container-crane', 'ground-track-field', 'harbor', 'helicopter', 'helipad',
                     'large-vehicle', 'plane', 'roundabout',
                     'ship', 'small-vehicle', 'soccer-ball-field',
                     'storage-tank', 'swimming-pool', 'tennis-court'],
        img_scale=(1024, 1024),
    ),
    Data2_DIOR_R=dict(
        data_root='./data/DIOR_R_dota/train_val',
        img_dir='images',
        ann_dir='labelTxt',
        pkl_ann_dir='Step6_Format_labels',
        class_names=['airplane', 'airport', 'baseballfield', 'basketballcourt',
                     'bridge', 'chimney', 'dam',
                     'Expressway-Service-area', 'Expressway-toll-station',
                     'golffield', 'groundtrackfield',
                     'harbor', 'overpass', 'ship', 'stadium', 'storagetank',
                     'tenniscourt', 'trainstation', 'vehicle', 'windmill'],
        img_scale=(1024, 1024),
    ),
    Data3_FAIR1M=dict(
        data_root='./data/FAIR1M_2_800_400/train',
        img_dir='images',
        ann_dir='annfiles',
        pkl_ann_dir='Step6_Format_labels',
        class_names=['a220', 'a321', 'a330', 'a350', 'arj21',
                     'baseball_field', 'basketball_court', 'boeing737', 'boeing747', 'boeing777', 'boeing787',
                     'bridge', 'bus', 'c919', 'cargo_truck', 'dry_cargo_ship', 'dump_truck',
                     'engineering_ship', 'excavator', 'fishing_boat', 'football_field', 'intersection',
                     'liquid_cargo_ship', 'motorboat', 'other-airplane', 'other-ship', 'other-vehicle',
                     'passenger_ship', 'roundabout',
                     'small_car', 'tennis_court', 'tractor', 'trailer', 'truck_tractor', 'tugboat', 'van', 'warship'],

        img_scale=(1024, 1024),
    ),
    Data5_SpaceNet=dict(
        data_root='./data/Spacenet_Merge/train',
        img_dir='images',
        ann_dir='annotations',
        pkl_ann_dir='Step6_Format_labels',
        class_names=['building',],
        img_scale=(832, 832),
    ),
    Data6_Xview=dict(
        data_root='./data/xView_New_800_600/train',
        img_dir='images',
        ann_dir='Step1_Trans_HBB2OBB',
        pkl_ann_dir='Step6_Format_labels',
        class_names=['Aircraft_Hangar', 'Barge', 'Building', 'Bus', 'Cargo_Truck',
                     'Cargo_or_Container_Car', 'Cement_Mixer', 'Construction_Site',
                     'Container_Crane', 'Container_Ship', 'Crane_Truck', 'Damaged_Building',
                     'Dump_Truck', 'Engineering_Vehicle', 'Excavator', 'Facility', 'Ferry', 'Fishing_Vessel',
                     'Fixed-wing_Aircraft', 'Flat_Car', 'Front_loader_or_Bulldozer', 'Ground_Grader',
                     'Haul_Truck', 'Helicopter', 'Helipad', 'Hut_or_Tent', 'Locomotive', 'Maritime_Vessel',
                     'Mobile_Crane', 'Motorboat', 'Oil_Tanker', 'Passenger_Car', 'Passenger_Vehicle',
                     'Passenger_or_Cargo_Plane', 'Pickup_Truck', 'Pylon', 'Railway_Vehicle', 'Reach_Stacker',
                     'Sailboat', 'Scraper_or_Tractor', 'Shed', 'Shipping_Container', 'Shipping_container_lot',
                     'Small_Aircraft', 'Small_Car', 'Storage_Tank', 'Straddle_Carrier', 'Tank_car', 'Tower',
                     'Tower_crane', 'Trailer', 'Truck', 'Truck_Tractor', 'Truck_Tractor_with_Box_Trailer',
                     'Truck_Tractor_with_Flatbed_Trailer', 'Truck_Tractor_with_Liquid_Tank', 'Tugboat',
                     'Utility_Truck', 'Vehicle_Lot', 'Yacht'],
        img_scale=(832, 832),
    ),
    Data7_HRSC2016=dict(
        data_root='./data/HRSC2016_DOTA/train',
        img_dir='images',
        ann_dir='labelTxt',
        pkl_ann_dir='Step6_Format_labels',
        class_names=['Arleigh_Burke', 'Austen', 'Car_carrier', 'CntShip', 'Container', 'Cruise',
                     'Enterprise', 'Hovercraft', 'Kuznetsov', 'Medical', 'Midway_class', 'Nimitz',
                     'OXo', 'Perry', 'Sanantonio', 'Tarawa', 'Ticonderoga',
                     'WhidbeyIsland', 'aircraft_carrier','lute', 'merchant_ship', 'ship', 'submarine', 'warcraft', 'yacht'],
        img_scale=(832, 832),
    ),
    Data8_GLH_Bridge=dict(
        data_root='./data/GLH-Bridge_1024_200/train',
        img_dir='images',
        ann_dir='annfiles',
        pkl_ann_dir='Step6_Format_labels',
        class_names=['bridge'],
        img_scale=(1024, 1024),
    ),
    Data11_WHU_Mix=dict(
        data_root='./data/WHU_Mix/train',
        img_dir='images',
        ann_dir='labelTxt',
        pkl_ann_dir='Step6_Format_labels_wo_embeds',
        class_names=['building'],
        img_scale=(832, 832),
    ),
    Data12_ShipImageNet=dict(
        data_root='./data/ShipRSImageNet_DOTA/train',
        img_dir='images',
        ann_dir='labelTxt',
        pkl_ann_dir='Step6_Format_labels',
        class_names=['aoe', 'arleigh_burke_dd', 'asagiri_dd', 'atago_dd',
                     'austin_ll', 'barge', 'cargo', 'commander', 'container_ship',
                     'dock', 'enterprise', 'epf', 'ferry', 'fishing_vessel',
                     'hatsuyuki_dd', 'hovercraft', 'hyuga_dd', 'lha_ll', 'lsd_41_ll',
                     'masyuu_as', 'medical_ship', 'midway', 'motorboat', 'nimitz',
                     'oil_tanker', 'osumi_ll', 'other_aircraft_carrier',
                     'other_auxiliary_ship', 'other_destroyer', 'other_frigate',
                     'other_landing', 'other_merchant', 'other_ship', 'other_warship',
                     'patrol', 'perry_ff', 'roro', 'sailboat', 'sanantonio_as',
                     'submarine', 'test_ship', 'ticonderoga', 'training_ship', 'tugboat',
                     'wasp_ll', 'yacht', 'yudao_ll', 'yudeng_ll', 'yuting_ll', 'yuzhao_ll'],
        img_scale=(832, 832),
    ),

)
